title: My first presentation with jekyll!!
author: Zardyez on GitHub
email: satazai2011@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  HEY! thanks for coming over, anyways cya!!!
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Zardyez # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
