title: idk
author: GitHub User: Zardyez
email: satazai2011@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   hi ok bye

# social links
github_username:  Zardyez # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
