title: My first presentation with jekyll and github!
author: Zardyez on github
email: satazai2011@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  HEY! thanks for coming over, anyways cya
# social links
github_username:  Zardyez # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
